[package]
name = "chat-application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping-rs = "0.1.2"
regex = "1.10.4"
